// Auto-generated by `npx boneyard-js scan` — do not edit
import { registerBones } from 'boneyard-js/native'

import _product_card from './product-card.bones.json'

registerBones({
  "product-card": _product_card,
})
